# Generated by Django 5.0.6 on 2024-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_baranggay_item_btype_item_citizenship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Baranggay',
            new_name='Brgy',
        ),
    ]
