# Generated by Django 5.0.6 on 2024-07-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_baranggay_item_brgy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Brgy',
            new_name='Baranggay',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Btype',
            new_name='Bloodtype',
        ),
    ]
