# Generated by Django 5.0.6 on 2024-07-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_brgy_item_baranggay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Bloodtype',
            new_name='Btype',
        ),
    ]
